apiVersion: v1
kind: Service
metadata:
  name: {{ include "callman.fullname" . }}-admin
  labels:
    {{- include "callman.labels" (dict "root" $ "component" "admin") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5100
      targetPort: http
  selector:
    {{- include "callman.selectorLabels" (dict "root" $ "component" "admin") | nindent 4 }}
