apiVersion: v1
kind: Service
metadata:
  name: {{ include "callman.fullname" . }}-backend
  labels:
    {{- include "callman.labels" (dict "root" $ "component" "backend") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
  selector:
    {{- include "callman.selectorLabels" (dict "root" $ "component" "backend") | nindent 4 }}
